# Generated by Django 4.1.7 on 2023-03-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='channel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('text', 'Texto')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.file')),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelContentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.channel')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.content')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='contents',
            field=models.ManyToManyField(through='immfly_content_app.ChannelContentRelation', to='immfly_content_app.content'),
        ),
        migrations.AddField(
            model_name='channel',
            name='subchannels',
            field=models.ManyToManyField(blank=True, to='immfly_content_app.channel'),
        ),
    ]
