# Generated by Django 4.1.7 on 2023-04-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immfly_content_app', '0003_channel_contents_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='contents',
        ),
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='immfly_content_app.channel'),
        ),
    ]
