# Generated by Django 4.1.7 on 2023-04-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immfly_content_app', '0004_remove_channel_contents_content_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.file'),
        ),
        migrations.AlterField(
            model_name='content',
            name='metadata',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.metadata'),
        ),
    ]
