# Generated by Django 4.1.7 on 2023-04-10 10:20

from django.db import migrations, models
import django.db.models.deletion
import immfly_content_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('immfly_content_app', '0005_alter_content_file_alter_content_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.file'),
        ),
        migrations.AlterField(
            model_name='content',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immfly_content_app.metadata'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='content_files/', validators=[immfly_content_app.validators.validate_file_extension]),
        ),
    ]
